-- SHOWS CUSTOMERS FROM RUSSIA OR POLAND AND AMOUNT SPENT IS GREATER THAN THE AVERAGE AMOUNT SPENT 

SELECT C.CUSTOMER_NAME, CO.COUNTRY_NAME, C.CUSTOMER_AMOUNTSPENT
FROM CUSTOMERS C
INNER JOIN COUNTRY CO
ON C.CUSTOMER_COUNTRYID = CO.COUNTRY_ID
WHERE CO.COUNTRY_NAME = 'Russia'
OR CO.COUNTRY_NAME = 'Poland'
AND C.CUSTOMER_AMOUNTSPENT > (
    SELECT AVG(CUSTOMER_AMOUNTSPENT)
    FROM CUSTOMERS);


SELECT AVG(CUSTOMER_AMOUNTSPENT)
FROM CUSTOMERS;

--  The most expenisve piece of art and it's artist 

SELECT A.A_NAME, P.PRICE, P.TITLE
FROM ARTISTS A
INNER JOIN artists_make_piecesofart AM
ON A.A_NAME = AM.Artist_name
INNER JOIN PIECEsOFART P
ON AM.PIECEofart_TITLE = P.TITLE
WHERE P.PRICE =
    (SELECT MAX(PRICE)
        FROM PIECESOFART)

-- Artists with at least 3 followers

SELECT A.A_NAME, A.A_STYLEOFART, COUNT(C.C_NAME) AS FOLLOWERS
FROM ARTISTS A
LEFT JOIN CUSTOMER_FOLLOWS_ARTISTS C
ON A.A_NAME = C.AR_NAME
GROUP BY A.A_NAME, A.A_STYLEOFART
HAVING COUNT(C.C_NAME) > 2
ORDER BY FOLLOWERS DESC

-- Showing a list of artists between the age of 20 and 30 in ascending order

SELECT A_NAME, A_AGE 
FROM ARTISTS
WHERE A_AGE > 20
AND A_AGE < 30
ORDER BY A_AGE

-- DISPLAYS INFORMATION ABOUT ARTISTS WHO HAVE FOLLOWERS (CORRELATED SUBQUERY)
SELECT * FROM ARTISTS 
WHERE EXISTS 
    (SELECT AR_NAME FROM CUSTOMER_FOLLOWS_ARTISTS C 
    WHERE ARTISTS.A_NAME = C.AR_NAME);

-- It shows number of customers and sales per country
SELECT COUNTRY_NAME, COUNT(CUSTOMER_NAME) AS "NUMBER OF CUSTOMERS" , SUM(CUSTOMER_AMOUNTSPENT) AS SALES
FROM CUSTOMERS CU
LEFT JOIN COUNTRY CO
ON CU.CUSTOMER_COUNTRYID = CO.COUNTRY_ID
GROUP BY COUNTRY_NAME;
 
 -- SHOW YOUNGEST ARTIST WHO HAS A PIECE OF ART WORTH MORE THAN THE AVERAGE PRICE OF A PIECE OF ART

 SELECT A.A_NAME, A.A_AGE, P.TITLE, P.PRICE
FROM ARTISTS A
INNER JOIN ARTISTS_MAKE_PIECESOFART AMP
ON A.A_NAME = AMP.ARTIST_NAME
INNER JOIN PIECESOFART P
ON P.TITLE = AMP.PIECEOFART_TITLE
WHERE A.A_AGE = 
    (SELECT MIN(A_AGE)
    FROM ARTISTS)
AND P.PRICE > 
    (SELECT AVG(PRICE)
    FROM PIECESOFART)

-- SHOW LIST OF ART GROUPS 

SELECT * FROM ART_GROUP